<?php

namespace DefaultBundle\Repository;

/**
 * DzieciRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DzieciRepository extends \Doctrine\ORM\EntityRepository
{
}
