<?php

namespace DefaultBundle\Repository;

/**
 * KursyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KursyRepository extends \Doctrine\ORM\EntityRepository
{
}
