<?php

namespace DefaultBundle\Repository;

/**
 * LicznikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicznikRepository extends \Doctrine\ORM\EntityRepository
{
}
